### ISSUE TITLE
Typo mistake in client/components/studio/edit/EditSidebar.jsx

### ISSUE THREAD

**Issue by Dev-Code24** [cn10xdev/YouTube-clone#2]
When you login using the given email id and password, and navigate to the youtube studio.
Try going to the video details editing page, and then come back to the studio home page, using the "Channel content" button. 
This way you will be shown, that this page doesn't exists, but it did exist. That's the page you were redirected to when came to the studio page.
I have attached a video showing the demo to recreate the bug I am talking about.

Go through the code, observe the URL changes when navigating here and there, and check why you are being redirected to a page which does not exists even though it did exist.

https://github.com/user-attachments/assets/7580033e-ec61-4266-8976-26d04a6c6101

**Comment by shubham7522** [comment]
Please assign it to me

**Comment by Dev-Code24** [comment]
> Please assign it to me

I have assigned you, you can make a PR  now.

**Comment by shubham7522** [comment]
![image](https://github.com/user-attachments/assets/30c6de84-5bb8-496a-b5b4-47b3fd1e2074)
I just got this error while running the webapp locally

**Comment by shubham7522** [comment]
I followed the steps you listed in readme

**Comment by shubham7522** [comment]
![image](https://github.com/user-attachments/assets/8e601a63-cf4f-4d8d-a691-cc321f246433)
Also cannot login using given email and password

**Comment by Dev-Code24** [comment]
well the server link I provided was not changed to be used for localhost.
So here's the updated link to be used for the server
just do the same steps as mentioned in the Readme file, but change the URL to 

https://some-backend.vercel.app/

**Comment by Dev-Code24** [comment]
@shubham7522 
just wait for some time I am doing some extra checks on the server then you can proceed with your development on this issue

**Comment by shubham7522** [comment]
Ok

**Comment by Dev-Code24** [comment]
> Ok

now you can work on fixing this bug.

**Comment by shubham7522** [comment]
#5 Submitted the PR
